spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/website
    username: root
    password: ${password}
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      properties:
        format_sql: true